# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: arnab825.MissionControl
PackageVersion: 3.8.1
InstallerType: nullsoft
Scope: machine
InstallModes:
- interactive
- silent
- silentWithProgress
InstallerSwitches:
  Silent: /S
  SilentWithProgress: /S
UpgradeBehavior: install
Commands:
- MissionControl
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/arnab825/Mission-Control/releases/download/v3.8.1/MissionControl-Setup.exe
  InstallerSha256: 46AE8744D028712465F90D1C7D2E6875FED02D7D69D0C3B3860B5B6C27DBB2EB
ManifestType: installer
ManifestVersion: 1.6.0
